# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import temperatura_pb2 as temperatura__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in temperatura_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConvertirStub(object):
    """Definir funciones remotas
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CelciusFarenheit = channel.unary_unary(
                '/Convertir/CelciusFarenheit',
                request_serializer=temperatura__pb2.Parametros.SerializeToString,
                response_deserializer=temperatura__pb2.Resultado.FromString,
                _registered_method=True)
        self.FarenheitCelcius = channel.unary_unary(
                '/Convertir/FarenheitCelcius',
                request_serializer=temperatura__pb2.Parametros.SerializeToString,
                response_deserializer=temperatura__pb2.Resultado.FromString,
                _registered_method=True)


class ConvertirServicer(object):
    """Definir funciones remotas
    """

    def CelciusFarenheit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FarenheitCelcius(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConvertirServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CelciusFarenheit': grpc.unary_unary_rpc_method_handler(
                    servicer.CelciusFarenheit,
                    request_deserializer=temperatura__pb2.Parametros.FromString,
                    response_serializer=temperatura__pb2.Resultado.SerializeToString,
            ),
            'FarenheitCelcius': grpc.unary_unary_rpc_method_handler(
                    servicer.FarenheitCelcius,
                    request_deserializer=temperatura__pb2.Parametros.FromString,
                    response_serializer=temperatura__pb2.Resultado.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Convertir', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Convertir', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Convertir(object):
    """Definir funciones remotas
    """

    @staticmethod
    def CelciusFarenheit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Convertir/CelciusFarenheit',
            temperatura__pb2.Parametros.SerializeToString,
            temperatura__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FarenheitCelcius(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Convertir/FarenheitCelcius',
            temperatura__pb2.Parametros.SerializeToString,
            temperatura__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
