# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperatura.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'temperatura.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperatura.proto\"\x1b\n\nParametros\x12\r\n\x05valor\x18\x01 \x01(\x01\"\x1e\n\tResultado\x12\x11\n\tResultado\x18\x01 \x01(\x01\x32\x65\n\tConvertir\x12+\n\x10\x43\x65lciusFarenheit\x12\x0b.Parametros\x1a\n.Resultado\x12+\n\x10\x46\x61renheitCelcius\x12\x0b.Parametros\x1a\n.Resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperatura_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARAMETROS']._serialized_start=21
  _globals['_PARAMETROS']._serialized_end=48
  _globals['_RESULTADO']._serialized_start=50
  _globals['_RESULTADO']._serialized_end=80
  _globals['_CONVERTIR']._serialized_start=82
  _globals['_CONVERTIR']._serialized_end=183
# @@protoc_insertion_point(module_scope)
